In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataFrame =pd.read_csv("credit_train.csv")
data=dataFrame.copy()

In [3]:
data=data.drop(columns=['Loan ID','Customer ID'],axis=1)

In [4]:

data

Loan Status  Current Loan Amount        Term  Credit Score  \
0       Fully Paid             445412.0  Short Term         709.0   
1       Fully Paid             262328.0  Short Term           NaN   
2       Fully Paid           99999999.0  Short Term         741.0   
3       Fully Paid             347666.0   Long Term         721.0   
4       Fully Paid             176220.0  Short Term           NaN   
...            ...                  ...         ...           ...   
100509         NaN                  NaN         NaN           NaN   
100510         NaN                  NaN         NaN           NaN   
100511         NaN                  NaN         NaN           NaN   
100512         NaN                  NaN         NaN           NaN   
100513         NaN                  NaN         NaN           NaN   

        Annual Income Years in current job Home Ownership             Purpose  \
0           1167493.0              8 years  Home Mortgage   Home Improvements   
1                 NaN            10+ years  Home Mortgage  Debt Consolidation   
2           2231892.0              8 years       Own Home  Debt Consolidation   
3            806949.0              3 years       Own Home  Debt Consolidation   
4                 NaN              5 years           Rent  Debt Consolidation   
...               ...                  ...            ...                 ...   
100509            NaN                  NaN            NaN                 NaN   
100510            NaN                  NaN            NaN                 NaN   
100511            NaN                  NaN            NaN                 NaN   
100512            NaN                  NaN            NaN                 NaN   
100513            NaN                  NaN            NaN                 NaN   

        Monthly Debt  Years of Credit History  Months since last delinquent  \
0            5214.74                     17.2                           NaN   
1           33295.98                     21.1                           8.0   
2           29200.53                     14.9                          29.0   
3            8741.90                     12.0                           NaN   
4           20639.70                      6.1                           NaN   
...              ...                      ...                           ...   
100509           NaN                      NaN                           NaN   
100510           NaN                      NaN                           NaN   
100511           NaN                      NaN                           NaN   
100512           NaN                      NaN                           NaN   
100513           NaN                      NaN                           NaN   

        Number of Open Accounts  Number of Credit Problems  \
0                           6.0                        1.0   
1                          35.0                        0.0   
2                          18.0                        1.0   
3                           9.0                        0.0   
4                          15.0                        0.0   
...                         ...                        ...   
100509                      NaN                        NaN   
100510                      NaN                        NaN   
100511                      NaN                        NaN   
100512                      NaN                        NaN   
100513                      NaN                        NaN   

        Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens  
0                     228190.0             416746.0           1.0        0.0  
1                     229976.0             850784.0           0.0        0.0  
2                     297996.0             750090.0           0.0        0.0  
3                     256329.0             386958.0           0.0        0.0  
4                     253460.0             427174.0           0.0        0.0  
...                        ...       

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100514 entries, 0 to 100513
Data columns (total 17 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   Loan Status                   100000 non-null  object 
 1   Current Loan Amount           100000 non-null  float64
 2   Term                          100000 non-null  object 
 3   Credit Score                  80846 non-null   float64
 4   Annual Income                 80846 non-null   float64
 5   Years in current job          95778 non-null   object 
 6   Home Ownership                100000 non-null  object 
 7   Purpose                       100000 non-null  object 
 8   Monthly Debt                  100000 non-null  float64
 9   Years of Credit History       100000 non-null  float64
 10  Months since last delinquent  46859 non-null   float64
 11  Number of Open Accounts       100000 non-null  float64
 12  Number of Credit Problems     100000 non-nul

In [6]:
data['Loan Status'].unique()

array(['Fully Paid', 'Charged Off', nan], dtype=object)

In [7]:
data[data['Loan Status']=="Fully Paid"].shape

(77361, 17)

In [8]:
data[data['Loan Status']=="Charged Off"].shape

(22639, 17)

In [9]:
numerical_col=[]
categorical_col=[]
for i in data.columns:
    if data[i].dtype=='int64' or data[i].dtype=='float64':
        numerical_col.append(i)
    elif data[i].dtype=='O':
        categorical_col.append(i)
        

In [10]:
numerical_col

['Current Loan Amount',
 'Credit Score',
 'Annual Income',
 'Monthly Debt',
 'Years of Credit History',
 'Months since last delinquent',
 'Number of Open Accounts',
 'Number of Credit Problems',
 'Current Credit Balance',
 'Maximum Open Credit',
 'Bankruptcies',
 'Tax Liens']

In [11]:
len(numerical_col)

12

In [12]:
categorical_col

['Loan Status', 'Term', 'Years in current job', 'Home Ownership', 'Purpose']

In [13]:
len(categorical_col)

5

In [14]:
for i in numerical_col:
    mean_vlaue=data[i].mean()
    data[i]=data[i].fillna(mean_vlaue)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100514 entries, 0 to 100513
Data columns (total 17 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   Loan Status                   100000 non-null  object 
 1   Current Loan Amount           100514 non-null  float64
 2   Term                          100000 non-null  object 
 3   Credit Score                  100514 non-null  float64
 4   Annual Income                 100514 non-null  float64
 5   Years in current job          95778 non-null   object 
 6   Home Ownership                100000 non-null  object 
 7   Purpose                       100000 non-null  object 
 8   Monthly Debt                  100514 non-null  float64
 9   Years of Credit History       100514 non-null  float64
 10  Months since last delinquent  100514 non-null  float64
 11  Number of Open Accounts       100514 non-null  float64
 12  Number of Credit Problems     100514 non-nul

In [16]:
data

Loan Status  Current Loan Amount        Term  Credit Score  \
0       Fully Paid         4.454120e+05  Short Term    709.000000   
1       Fully Paid         2.623280e+05  Short Term   1076.456089   
2       Fully Paid         1.000000e+08  Short Term    741.000000   
3       Fully Paid         3.476660e+05   Long Term    721.000000   
4       Fully Paid         1.762200e+05  Short Term   1076.456089   
...            ...                  ...         ...           ...   
100509         NaN         1.176045e+07         NaN   1076.456089   
100510         NaN         1.176045e+07         NaN   1076.456089   
100511         NaN         1.176045e+07         NaN   1076.456089   
100512         NaN         1.176045e+07         NaN   1076.456089   
100513         NaN         1.176045e+07         NaN   1076.456089   

        Annual Income Years in current job Home Ownership             Purpose  \
0        1.167493e+06              8 years  Home Mortgage   Home Improvements   
1        1.378277e+06            10+ years  Home Mortgage  Debt Consolidation   
2        2.231892e+06              8 years       Own Home  Debt Consolidation   
3        8.069490e+05              3 years       Own Home  Debt Consolidation   
4        1.378277e+06              5 years           Rent  Debt Consolidation   
...               ...                  ...            ...                 ...   
100509   1.378277e+06                  NaN            NaN                 NaN   
100510   1.378277e+06                  NaN            NaN                 NaN   
100511   1.378277e+06                  NaN            NaN                 NaN   
100512   1.378277e+06                  NaN            NaN                 NaN   
100513   1.378277e+06                  NaN            NaN                 NaN   

        Monthly Debt  Years of Credit History  Months since last delinquent  \
0        5214.740000                17.200000                     34.901321   
1       33295.980000                21.100000                      8.000000   
2       29200.530000                14.900000                     29.000000   
3        8741.900000                12.000000                     34.901321   
4       20639.700000                 6.100000                     34.901321   
...              ...                      ...                           ...   
100509  18472.412336                18.199141                     34.901321   
100510  18472.412336                18.199141                     34.901321   
100511  18472.412336                18.199141                     34.901321   
100512  18472.412336                18.199141                     34.901321   
100513  18472.412336                18.199141                     34.901321   

        Number of Open Accounts  Number of Credit Problems  \
0                       6.00000                    1.00000   
1                      35.00000                    0.00000   
2                      18.00000                    1.00000   
3                       9.00000                    0.00000   
4                      15.00000                    0.00000   
...                         ...                        ...   
100509                 11.12853                    0.16831   
100510                 11.12853                    0.16831   
100511                 11.12853                    0.16831   
100512                 11.12853                    0.16831   
100513                 11.12853                    0.16831   

        Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens  
0                 228190.00000        416746.000000       1.00000   0.000000  
1                 229976.00000        850784.000000       0.00000   0.000000  
2                 297996.00000        750090.000000       0.00000   0.000000  
3                 256329.00000        386958.000000       0.00000   0.000000  
4                 253460.00000        427174.000000       0.00000   0.000000  
...                        ...       

In [17]:
data=data.dropna()

In [18]:
data

Loan Status  Current Loan Amount        Term  Credit Score  \
0      Fully Paid             445412.0  Short Term    709.000000   
1      Fully Paid             262328.0  Short Term   1076.456089   
2      Fully Paid           99999999.0  Short Term    741.000000   
3      Fully Paid             347666.0   Long Term    721.000000   
4      Fully Paid             176220.0  Short Term   1076.456089   
...           ...                  ...         ...           ...   
99994  Fully Paid             210584.0  Short Term    719.000000   
99995  Fully Paid             147070.0  Short Term    725.000000   
99996  Fully Paid           99999999.0  Short Term    732.000000   
99997  Fully Paid             103136.0  Short Term    742.000000   
99998  Fully Paid             530332.0  Short Term    746.000000   

       Annual Income Years in current job Home Ownership             Purpose  \
0       1.167493e+06              8 years  Home Mortgage   Home Improvements   
1       1.378277e+06            10+ years  Home Mortgage  Debt Consolidation   
2       2.231892e+06              8 years       Own Home  Debt Consolidation   
3       8.069490e+05              3 years       Own Home  Debt Consolidation   
4       1.378277e+06              5 years           Rent  Debt Consolidation   
...              ...                  ...            ...                 ...   
99994   7.833890e+05               1 year  Home Mortgage               Other   
99995   4.754370e+05              7 years       Own Home               other   
99996   1.289416e+06               1 year           Rent  Debt Consolidation   
99997   1.150545e+06              6 years           Rent  Debt Consolidation   
99998   1.717524e+06              9 years           Rent  Debt Consolidation   

       Monthly Debt  Years of Credit History  Months since last delinquent  \
0           5214.74                     17.2                     34.901321   
1          33295.98                     21.1                      8.000000   
2          29200.53                     14.9                     29.000000   
3           8741.90                     12.0                     34.901321   
4          20639.70                      6.1                     34.901321   
...             ...                      ...                           ...   
99994       3727.61                     17.4                     18.000000   
99995       2202.86                     22.3                     34.901321   
99996      13109.05                      9.4                     21.000000   
99997       7315.57                     18.8                     18.000000   
99998       9890.07                     15.0                     34.901321   

       Number of Open Accounts  Number of Credit Problems  \
0                          6.0                        1.0   
1                         35.0                        0.0   
2                         18.0                        1.0   
3                          9.0                        0.0   
4                         15.0                        0.0   
...                        ...                        ...   
99994                      6.0                        0.0   
99995                      5.0                        0.0   
99996                     22.0                        0.0   
99997                     12.0                        1.0   
99998                      8.0                        0.0   

       Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens  
0                    228190.0             416746.0           1.0        0.0  
1                    229976.0             850784.0           0.0        0.0  
2                    297996.0             750090.0           0.0        0.0  
3                    256329.0             386958.0           0.0        0.0  
4                    253460.0             427174.0           0.0        0.0  
...                       ...                  ...           ...        ...  
99994       

In [19]:
data['Annual Income'].values

array([1167493.        , 1378276.55984217, 2231892.        , ...,
       1289416.        , 1150545.        , 1717524.        ])

In [20]:
data

Loan Status  Current Loan Amount        Term  Credit Score  \
0      Fully Paid             445412.0  Short Term    709.000000   
1      Fully Paid             262328.0  Short Term   1076.456089   
2      Fully Paid           99999999.0  Short Term    741.000000   
3      Fully Paid             347666.0   Long Term    721.000000   
4      Fully Paid             176220.0  Short Term   1076.456089   
...           ...                  ...         ...           ...   
99994  Fully Paid             210584.0  Short Term    719.000000   
99995  Fully Paid             147070.0  Short Term    725.000000   
99996  Fully Paid           99999999.0  Short Term    732.000000   
99997  Fully Paid             103136.0  Short Term    742.000000   
99998  Fully Paid             530332.0  Short Term    746.000000   

       Annual Income Years in current job Home Ownership             Purpose  \
0       1.167493e+06              8 years  Home Mortgage   Home Improvements   
1       1.378277e+06            10+ years  Home Mortgage  Debt Consolidation   
2       2.231892e+06              8 years       Own Home  Debt Consolidation   
3       8.069490e+05              3 years       Own Home  Debt Consolidation   
4       1.378277e+06              5 years           Rent  Debt Consolidation   
...              ...                  ...            ...                 ...   
99994   7.833890e+05               1 year  Home Mortgage               Other   
99995   4.754370e+05              7 years       Own Home               other   
99996   1.289416e+06               1 year           Rent  Debt Consolidation   
99997   1.150545e+06              6 years           Rent  Debt Consolidation   
99998   1.717524e+06              9 years           Rent  Debt Consolidation   

       Monthly Debt  Years of Credit History  Months since last delinquent  \
0           5214.74                     17.2                     34.901321   
1          33295.98                     21.1                      8.000000   
2          29200.53                     14.9                     29.000000   
3           8741.90                     12.0                     34.901321   
4          20639.70                      6.1                     34.901321   
...             ...                      ...                           ...   
99994       3727.61                     17.4                     18.000000   
99995       2202.86                     22.3                     34.901321   
99996      13109.05                      9.4                     21.000000   
99997       7315.57                     18.8                     18.000000   
99998       9890.07                     15.0                     34.901321   

       Number of Open Accounts  Number of Credit Problems  \
0                          6.0                        1.0   
1                         35.0                        0.0   
2                         18.0                        1.0   
3                          9.0                        0.0   
4                         15.0                        0.0   
...                        ...                        ...   
99994                      6.0                        0.0   
99995                      5.0                        0.0   
99996                     22.0                        0.0   
99997                     12.0                        1.0   
99998                      8.0                        0.0   

       Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens  
0                    228190.0             416746.0           1.0        0.0  
1                    229976.0             850784.0           0.0        0.0  
2                    297996.0             750090.0           0.0        0.0  
3                    256329.0             386958.0           0.0        0.0  
4                    253460.0             427174.0           0.0        0.0  
...                       ...                  ...           ...        ...  
99994       

In [21]:
data['Loan Status'].unique()

array(['Fully Paid', 'Charged Off'], dtype=object)

# Label Encoding

In [22]:
from sklearn.preprocessing import LabelEncoder


In [23]:
label_encoder=LabelEncoder()

In [24]:
categorical_col

['Loan Status', 'Term', 'Years in current job', 'Home Ownership', 'Purpose']

In [ ]:
#print(data['Term'].unique())
#label_encoder.fit_transform(data['Term'].unique())

In [ ]:
# print(data['Loan Status'].unique())
# label_encoder.fit_transform(data['Loan Status'].unique())

In [ ]:
# print(data['Years in current job'].unique())
# label_encoder.fit_transform(data['Years in current job'].unique())

In [ ]:
# print(data['Home Ownership'].unique())
# label_encoder.fit_transform(data['Home Ownership'].unique())

In [51]:
# print(data['Purpose'].unique())
# label_encoder.fit_transform(data['Purpose'].unique())

In [52]:
# print(data['Purpose'].unique())

In [27]:
for i in categorical_col:
    unique_data=[]
    print(data[i].unique())
    unique_data=data[i].unique()
    
    data[i]=label_encoder.fit_transform(data[i])
    file_save="encoder_data\\"+i+"_label_encoder.csv"
    print(data[i].unique())
    label_encoder_data=[unique_data,label_encoder.fit_transform(data[i].unique())]
    df = pd.DataFrame(label_encoder_data)
    
    df.to_csv(file_save)
    
   
    
    

['Fully Paid' 'Charged Off']
[1 0]
['Short Term' 'Long Term']


C:\Users\RajPanjwani\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


[1 0]
['8 years' '10+ years' '3 years' '5 years' '< 1 year' '2 years' '4 years'
 '9 years' '7 years' '1 year' '6 years']
[ 8  1  3  5 10  2  4  9  7  0  6]
['Home Mortgage' 'Own Home' 'Rent' 'HaveMortgage']
[1 2 3 0]
['Home Improvements' 'Debt Consolidation' 'Buy House' 'Business Loan'
 'Buy a Car' 'other' 'major_purchase' 'Take a Trip' 'Other'
 'small_business' 'Medical Bills' 'wedding' 'vacation'
 'Educational Expenses' 'moving' 'renewable_energy']
[ 5  3  1  0  2 11  9  8  7 13  6 15 14  4 10 12]


In [28]:
data

Loan Status  Current Loan Amount  Term  Credit Score  Annual Income  \
0                1             445412.0     1    709.000000   1.167493e+06   
1                1             262328.0     1   1076.456089   1.378277e+06   
2                1           99999999.0     1    741.000000   2.231892e+06   
3                1             347666.0     0    721.000000   8.069490e+05   
4                1             176220.0     1   1076.456089   1.378277e+06   
...            ...                  ...   ...           ...            ...   
99994            1             210584.0     1    719.000000   7.833890e+05   
99995            1             147070.0     1    725.000000   4.754370e+05   
99996            1           99999999.0     1    732.000000   1.289416e+06   
99997            1             103136.0     1    742.000000   1.150545e+06   
99998            1             530332.0     1    746.000000   1.717524e+06   

       Years in current job  Home Ownership  Purpose  Monthly Debt  \
0                         8               1        5       5214.74   
1                         1               1        3      33295.98   
2                         8               2        3      29200.53   
3                         3               2        3       8741.90   
4                         5               3        3      20639.70   
...                     ...             ...      ...           ...   
99994                     0               1        7       3727.61   
99995                     7               2       11       2202.86   
99996                     0               3        3      13109.05   
99997                     6               3        3       7315.57   
99998                     9               3        3       9890.07   

       Years of Credit History  Months since last delinquent  \
0                         17.2                     34.901321   
1                         21.1                      8.000000   
2                         14.9                     29.000000   
3                         12.0                     34.901321   
4                          6.1                     34.901321   
...                        ...                           ...   
99994                     17.4                     18.000000   
99995                     22.3                     34.901321   
99996                      9.4                     21.000000   
99997                     18.8                     18.000000   
99998                     15.0                     34.901321   

       Number of Open Accounts  Number of Credit Problems  \
0                          6.0                        1.0   
1                         35.0                        0.0   
2                         18.0                        1.0   
3                          9.0                        0.0   
4                         15.0                        0.0   
...                        ...                        ...   
99994                      6.0                        0.0   
99995                      5.0                        0.0   
99996                     22.0                        0.0   
99997                     12.0                        1.0   
99998                      8.0                        0.0   

       Current Credit Balance  Maximum Open Credit  Bankruptcies  Tax Liens  
0                    228190.0             416746.0           1.0        0.0  
1                    229976.0             850784.0           0.0        0.0  
2                    297996.0             750090.0           0.0        0.0  
3                    256329.0             386958.0           0.0        0.0  
4                    253460.0             427174.0           0.0        0.0  
...                       ...                  ...           ...        ...  
99994                   456.0             259160.0           0.0        0.0  
99995                 47766.0             658548.0           0.0        0.0  
99996                1530

# train test split

In [29]:
from sklearn.tree import DecisionTreeClassifier,export_graphviz,plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [30]:
data.columns

Index(['Loan Status', 'Current Loan Amount', 'Term', 'Credit Score',
       'Annual Income', 'Years in current job', 'Home Ownership', 'Purpose',
       'Monthly Debt', 'Years of Credit History',
       'Months since last delinquent', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens'],
      dtype='object')

In [31]:
X=data[['Current Loan Amount', 'Term', 'Credit Score',
       'Annual Income', 'Years in current job', 'Home Ownership', 'Purpose',
       'Monthly Debt', 'Years of Credit History',
       'Months since last delinquent', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens']]
Y=data[['Loan Status']]

In [32]:
X.head(7)

Current Loan Amount  Term  Credit Score  Annual Income  \
0             445412.0     1    709.000000   1.167493e+06   
1             262328.0     1   1076.456089   1.378277e+06   
2           99999999.0     1    741.000000   2.231892e+06   
3             347666.0     0    721.000000   8.069490e+05   
4             176220.0     1   1076.456089   1.378277e+06   
5             206602.0     1   7290.000000   8.968570e+05   
6             217646.0     1    730.000000   1.184194e+06   

   Years in current job  Home Ownership  Purpose  Monthly Debt  \
0                     8               1        5       5214.74   
1                     1               1        3      33295.98   
2                     8               2        3      29200.53   
3                     3               2        3       8741.90   
4                     5               3        3      20639.70   
5                     1               1        3      16367.74   
6                    10               1        3      10855.08   

   Years of Credit History  Months since last delinquent  \
0                     17.2                     34.901321   
1                     21.1                      8.000000   
2                     14.9                     29.000000   
3                     12.0                     34.901321   
4                      6.1                     34.901321   
5                     17.3                     34.901321   
6                     19.6                     10.000000   

   Number of Open Accounts  Number of Credit Problems  Current Credit Balance  \
0                      6.0                        1.0                228190.0   
1                     35.0                        0.0                229976.0   
2                     18.0                        1.0                297996.0   
3                      9.0                        0.0                256329.0   
4                     15.0                        0.0                253460.0   
5                      6.0                        0.0                215308.0   
6                     13.0                        1.0                122170.0   

   Maximum Open Credit  Bankruptcies  Tax Liens  
0             416746.0           1.0        0.0  
1             850784.0           0.0        0.0  
2             750090.0           0.0        0.0  
3             386958.0           0.0        0.0  
4             427174.0           0.0        0.0  
5             272448.0           0.0        0.0  
6             272052.0           1.0        0.0

In [33]:
Y

Loan Status
0                1
1                1
2                1
3                1
4                1
...            ...
99994            1
99995            1
99996            1
99997            1
99998            1

[95778 rows x 1 columns]

In [34]:
Y[Y['Loan Status']==0]

Loan Status
5                0
7                0
16               0
20               0
22               0
...            ...
99960            0
99975            0
99981            0
99988            0
99989            0

[21367 rows x 1 columns]

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=100)

# Creating Model

In [36]:
model=DecisionTreeClassifier(criterion='gini',max_depth=8)

In [37]:
model.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=8, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [38]:
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))
 


<IPython.core.display.Javascript object>

In [39]:
with open("D_tree.dot","w") as f:
    f=export_graphviz(model,feature_names=X.columns,out_file=f)

In [40]:
y_predict=model.predict(X_test)


In [41]:
y_predict

array([1, 1, 1, ..., 1, 1, 1])

In [42]:
accuracy_score(y_test,y_predict)*100

82.11874434467877

In [43]:
model.predict([[445412.0,1,709.000000,1.167493e+06,8,1,5,5214.74,17.2,34.901321,6.0,1.0,228190.0,416746.0,1.0,0.0]])

array([1])

In [44]:
model.predict([[206602.0,1,7290.000000,8.968570e+05,1,1,3,16367.74,17.3,34.901321,6.0,0.0,215308.0,272448.0,0.0,0.0]])

array([0])

In [45]:
model.feature_importances_

array([1.17956762e-01, 3.75313067e-02, 7.82583499e-01, 2.67070008e-02,
       0.00000000e+00, 1.27215266e-02, 8.15010516e-04, 8.09795924e-03,
       1.40208997e-03, 1.17681041e-03, 3.89718392e-04, 0.00000000e+00,
       2.35440720e-03, 8.26391015e-03, 0.00000000e+00, 0.00000000e+00])

In [46]:
for i in range(0, len(X.columns)):
    print(X.columns[i] ," --> "  ,model.feature_importances_[i])

Current Loan Amount  -->  0.11795676155616171
Term  -->  0.0375313067231158
Credit Score  -->  0.7825834985017096
Annual Income  -->  0.026707000756779193
Years in current job  -->  0.0
Home Ownership  -->  0.012721526581496913
Purpose  -->  0.0008150105162892365
Monthly Debt  -->  0.008097959240845352
Years of Credit History  -->  0.0014020899723652832
Months since last delinquent  -->  0.0011768104050945644
Number of Open Accounts  -->  0.0003897183919815788
Number of Credit Problems  -->  0.0
Current Credit Balance  -->  0.0023544072015637373
Maximum Open Credit  -->  0.008263910152597044
Bankruptcies  -->  0.0
Tax Liens  -->  0.0


### Displaying Image

In [47]:
# to make a tree from dot file ----------   http://www.webgraphviz.com/

In [48]:
#this is same as dot file
#here inplace of feature Name feature_1,feature_2 is writtern 

from sklearn.tree import export_text
text_representation = export_text(model)
print(text_representation)

|--- feature_2 <= 3483.23
|   |--- feature_0 <= 789140.00
|   |   |--- feature_1 <= 0.50
|   |   |   |--- feature_2 <= 912.23
|   |   |   |   |--- feature_3 <= 1405458.50
|   |   |   |   |   |--- feature_2 <= 689.50
|   |   |   |   |   |   |--- feature_5 <= 2.50
|   |   |   |   |   |   |   |--- feature_3 <= 1107785.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_3 >  1107785.50
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |--- feature_5 >  2.50
|   |   |   |   |   |   |   |--- feature_7 <= 27156.79
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_7 >  27156.79
|   |   |   |   |   |   |   |   |--- class: 0
|   |   |   |   |   |--- feature_2 >  689.50
|   |   |   |   |   |   |--- feature_2 <= 725.50
|   |   |   |   |   |   |   |--- feature_0 <= 351637.00
|   |   |   |   |   |   |   |   |--- class: 1
|   |   |   |   |   |   |   |--- feature_0 >  351637.00
|   |   |   |   |   |   |   | 

### Loading Model

In [49]:
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

<IPython.core.display.Javascript object>

0.8211874434467877


In [50]:
loaded_model.predict([[445412.0,1,709.000000,1.167493e+06,8,1,5,5214.74,17.2,34.901321,6.0,1.0,228190.0,416746.0,1.0,0.0]])

array([1])